language: node_js

node_js:
- lts/*
- node

services:
- docker

env:
  global:
  - NODE_DOWNLOAD_URL=https://nodejs.org/dist/v12.16.1/node-v12.16.1-win-x64.zip
  - NSIS_IMAGE=cs8898/nsis:latest

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- yarn install
- yarn build
- mkdir -p ./dist_install/bin
- cp -r ./dist ./dist_install/bin && cp -r ./node_modules ./dist_install/bin && cp
  ./package.json ./dist_install/bin && cp ./src/favicon.ico ./dist_install/bin
- mkdir -p node_download && wget -q $NODE_DOWNLOAD_URL -O ./node_download/node_rel.zip
  && cd ./node_download && unzip node_rel.zip 1>/dev/null && cd $TRAVIS_BUILD_DIR
- cp ./node_download/node-*/node.exe ./dist_install/bin
- docker run --rm -i -v $PWD:/tmp/build -u $(id -u $USER):$(id -g $USER) $NSIS_IMAGE
  /tmp/build/nsis/nsis.nsi

before_deploy:
- git config --local user.name "Travis CI"
- git config --local user.email "build@travis-ci.org"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: BxkgSQUlu8g9Q7vg82U6nOwm8C4g5L7fE9iaWnQgr5/S+6LyVncLy6DjzKomnqJAKxqXJLWvE4mkwjEKBKBUhsGi13Aj4o733ohTkWrH/BDU5pB5E9wAWqhdo5YKKO14hm+LwcbPhao+0eG4X2shziLvBkNV165VRFt+VQUALbVHpELBlFRrKG+KCo8cuEFErULU9sukcAhIwuXhlBHtnmPIXFknx6QE5jX1FdYAcX5I/lfJ0BJYLEnwYGshTtJRc5BXyFVaBxdfCYRLh69ItV8fQK/sT+K3RxmpZ2DY40C38SQ9SyBf3mXt1sFwhSbUtl+c8eT3UeLIFGkYOgoIkIIV+yMW10jAxqmGacnTQHvjk9zWBcC2HlyGJdHoea27NZmyjIF+XugilYRz+kGBw2fBXya5XV/zzLrWfr08QI/DpNoDY34YyJs2a1MDf26pBtV0Sp3fx17wAGBDSOF+TTUdd9TMcL/6Eq+drJKti2Ym0EcyI0K52+gfSGcqfqSEhCJh9Bp2sQNPftrLnFflcZOGE8cJ8hZ30319ZQpAH6dm5m17tJkreLroYSDITredAI4Q8icFavcVnt95iw8SS6F7tafNVp7FiMc3N5ir8QIrmmiZu0qweYr6kZlzpLZ58j+iV2lNEXmohRwd6a2DxzEJshJV/l14mhG5CqWitEo=
  file: "./dist_install/TANlockManager-Server-Setup.exe"
  skip_cleanup: true
  on:
    branch: master
    node_js: lts/*
    repo: FATH-Mechatronics/TANlockManager-Server
